export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const ACCEPT_SEARCH_RESULTS = 'ACCEPT_SEARCH_RESULTS';

export const FETCH_INGREDIENT_DETAIL = 'FETCH_INGREDIENT_DETAIL';
export const RECEIVE_INGREDIENT_DETAIL = 'RECEIVE_INGREDIENT_DETAIL';

export const FETCH_SYMPTOM_LIST = 'FETCH_SYMPTOM_LIST';
export const RECEIVE_SYMPTOM_LIST = 'RECEIVE_SYMPTOM_LIST';
